### PR TITLE
Adds previous|next buttons and several layout enhancements

### PR DESCRIPTION
**Pull request by BertrandBordage**
# Blog post before this pull request
selection_719
selection_720

# Blog post after this pull request
selection_714
selection_715

### CODE REVIEW

**Comment by kaedroho** [comment]
I've just pushed these changes to: http://wagtailnewlook.kaed.uk/

**Comment by gasman** [comment]
Thanks @BertrandBordage! A couple of initial thoughts from me...

* I'd prefer not to set SESSION_ENGINE to cached_db - the [Django docs](https://docs.djangoproject.com/en/1.7/topics/http/sessions/) recommend only using it with a proper cache backend (like Memcached or Redis), and for a demo site it's not really important to eliminate every possible DB query. I think it's best to keep wagtaildemo running on default Django settings as much as possible (unless there are clear benefits from changing - e.g. Postgres rather than Sqlite), so that people don't blindly copy them to production sites without doing their own research, or assume that those settings are necessary for Wagtail to work correctly.
* The previous/next buttons certainly look a lot nicer than the old menu, although to me it seems like quite an odd way of navigating a whole site. I guess the most important question is: which one is likely to be most useful as an example to Wagtail site developers? (Interested to hear more opinions on this...)
* Changing the carousel style so that the link is on a button rather than the entire image: I think the original version was intended to represent a "hero panel" like on http://www.ox.ac.uk/, where linking to other pages is the most important feature. With this change, it becomes more of a photo gallery - which is not a bad thing, but it might lead to people wondering why the 'carousel item' object is so complex. ("What's all this embed URL / document link business? Why can't it just be a list of images?") Again, more opinions on this would be welcome...
* Using IDs in CSS selectors is generally not recommended, as it makes the selectors too specific and hard to control. I'm not sure how religious we are about this for wagtaildemo, though :-)

Passing on to @davecranwell to review the stylistic / frontend aspects.

**Comment by BertrandBordage** [comment]
@gasman :

In a general way, your response says something about the quality of Wagtail, considering we’re only talking about the demo! I like it.

1. Using locmem as we currently do, `cached_db` has only one possible issue: if a session key is deleted and the demo site is served using multiple processes, then another process may reuse the deleted session key. But since I thought we weren’t considering using multiple processes to serve a demo site, I considered it being an irrelevant issue.  But your arguments about minimum settings are correct, I’ll remove it.  (I tried to remove every possible extra SQL query as I am serving the demo on an Olinuxino [an alternative to Raspberry Pi] and it is a bit slow).
2. Currently, previous/next buttons are the navigation way my clients prefer. The other well-known alternative is to show similar articles given the tags of each article, but that’s irrelevant considering the amount of data in this demo.  (By the way, is there a random data generator for Wagtail to stress test it?) Since I’m not a webdesign expert, your team probably has more ideas about this :)
3. The problem with a link on all the image is that we end up clicking on it by error while we wanted to click on the controls of the carousel. Another issue is that we can’t play videos when a carousel item has a video and a link.  Another solution is to make a link on all the caption block, and write a default caption if there is a link without a caption.
4. I’m not a CSS expert so you’ll probably have the final say. I just thought “the main content and the advert list will always appear one time on the document”.  Since IDs are always more efficient than classes, I thought that would be appropriate.

About the green background of the carousel captions, I’m not a big fan. Adding a background is a proposition to enhance readability. I tried to introduce the wagtail color, but it’s a bit ugly for now, as the rest of the site doesn’t follow.

**Comment by davecranwell** [comment]
Happy with this from a FE perspective. Merge at will.

**Pull request merged**
