### PR TITLE
Removing outdated admin credentials from readme file

### PR DESCRIPTION
**Pull request by Chris-May**
This will help newcomers to this project, and prevent further issues like #21.

### CODE REVIEW

**Comment by gasman** [comment]
Hi @Chris-May,
These login details aren't outdated - they were added in #44 to cater for setups such as Heroku that don't give you direct command-line access, and the account is still in place in the current version of the demo (https://github.com/torchbox/wagtaildemo/blob/master/demo/fixtures/demo.json#L1048-1065).

**Comment by Chris-May** [comment]
Hmmm. Could the password have changed? I can't log in with `admin / changeme`.

**Comment by gasman** [comment]
How did you set up the site - with, or without Vagrant?

**Comment by Chris-May** [comment]
With Vagrant

**Comment by gasman** [comment]
Hmm, afraid I don't know what's going on there, then - I regularly bring up wagtaildemo Vagrant boxes as part of testing new Wagtail releases (including yesterday's 1.5 release) and the default `admin / changeme` details always work for me.

**Comment by Chris-May** [comment]
Well, if it's working for other people, I'm happy. I can still create a super user and move forward.

Thanks for your time!

**Pull request closed without merging**
