### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by kaedroho**
This Dockerfile builds a fully working wagtaildemo image with the database and image files baked into it.

This means that you don't have to run any commands (migrate, load_initial_data, etc) to set it up. And also allows the data to be easily reverted by recreating the container. (I wouldn't recommend running a production site like this though!)

Some of this PR (requirements, settings and wsgi) could be merged with the heroku configuration.

To build the image run the following command (from the root of the repo):
```
docker build -t wagtaildemo .
```
(nows a good time to get a coffee)

Once it's built, you can either run it in the foreground or as a daemon.

To run the the foreground, use the following command:
```
docker run -ti -p 8000:80 wagtaildemo
```

To run as a daemon, use the following command:
```
docker run -d -p 8000:80 wagtaildemo
```

(in both cases, it will run on port 8000)

### CODE REVIEW

**Comment by kaedroho** [comment]
See it here: http://wagtaildemodocker.kaed.uk

**Comment by gasman** [comment]
Are you proposing to use this for the Torchbox-hosted public instance of wagtaildemo, as a development environment, or something else? As per previous discussions (e.g. #59) we should avoid the temptation to bundle everyone's pet deployment tool into wagtaildemo "just because we can" - we ought to decide what purpose(s) wagtaildemo is meant to serve, and stick with the code/configuration that works towards those aims.

Last time we had this discussion, we decided that wagtaildemo would be focused purely on being a hosted online demo, and everything else would be a side effect. Evidently we've backtracked a bit on that decision, since we're now officially pushing it as a means for developing Wagtail as well, e.g. in http://docs.wagtail.io/en/latest/contributing/developing.html. That's not a bad thing, but if we're going to start using wagtaildemo for new purposes - like, say, demonstrating best practices for deployment on various platforms - then we should A) formally state that as a goal, and B) consider whether wagtaildemo is really the best tool for the job.

**Comment by kaedroho** [comment]
It was agreed in the last team meeting (and one a month ago) to use Docker to host ``demo.wagtail.io``. The reason being is Docker makes it easy to roll back the database and media.

**Comment by gasman** [comment]
Ah, cool - fair enough :-)

**Comment by kaedroho** [comment]
Once this is merged, I'll look into removing the heroku-specific, settings, requirements, etc. Everything but the Dockerfile can be shared which would make this all much neater.

**Pull request closed without merging**
