### PR TITLE
Update search_results.html

### PR DESCRIPTION
**Pull request by johnfraney**
Replace smart quotation marks with regular quotes

### CODE REVIEW

**Comment by gasman** [comment]
It looks like this never gets displayed anyhow, because the correct variable is `query`, not `q`...

@johnfraney Any particular reason for this change?

**Comment by johnfraney** [comment]
@gasman My linter threw some errors about the quotation marks when I used that page as a starting point and it was an easy fix. Looks like it would make good sense to change that `q` to `query` also, or just get rid of that chunk of code altogether.

**Comment by gasman** [comment]
Query parameter now fixed in bb816026498a013d158ad59ce6b3268fce501d53 - thanks for highlighting this!

On balance I'd rather stick with the curly quotes - they are valid HTML (so if anything, the linter is in error for flagging it up) and having more "proper" typography on the web can only be a good thing...

**Comment by johnfraney** [comment]
Huh! I learned something today. Bye-bye `&#8220;`. Thanks for putting together this demo site. The menu template tag has been a great resource for me.

**Pull request closed without merging**
