### PR TITLE
Make it a proper Python package

### PR DESCRIPTION
**Pull request by ipmb**
This makes the Django project pip installable. I haven't tested the Vagrant files, but the changes are pretty minor.

### CODE REVIEW

**Comment by gasman** [comment]
Hi @ipmb,
Thanks for this! Could you perhaps elaborate on what the advantage of this approach is? Generally we'd want to keep `wagtaildemo`'s setup as close as possible to the usual Django project setup process that developers are familiar with - to avoid giving the impression that Wagtail is doing anything non-standard - and the idea of packaging Django projects up to be pip installable isn't something I've encountered before.

(Have just tried setting this up according to the new instructions in the readme, and it looks like there are a few paths that still need fixing up: `pip install -e wagtaildemo -r requirements/dev.txt` should be `pip install -e wagtaildemo -r wagtaildemo/requirements/dev.txt`, and the load_initial_data step fails for me with `No such file or directory: 'wagtaildemo/wagtaildemo/settings/../../demo/fixtures/images'`)

**Comment by ipmb** [comment]
I think this is a pretty standard approach for Django, but really Python as a whole. A common thing you'll hear in the community is that "Django is just Python" and this is the preferred method to distribute Python modules. Using `pip install -e` ([editable](https://pip.pypa.io/en/latest/reference/pip_install.html#editable-installs)) gives users a simple way to get the project on their Python path and modify the source if they want.

Putting your apps (`demo`) in the namespace of your project (`wagtaildemo`) is also a very common and (I believe) preferred method of organizing Django projects.

Having a `setup.py` would also let somebody install it directly from git: `pip install -e git+https://github.com/torchbox/wagtaildemo.git#egg=wagtaildemo`.

There aren't really any drawbacks to this approach, but it makes things more "Pythonic" which I would consider a Django best practice.

*I'll fix up the paths you mentioned and add a commit to this branch today.*

**Comment by ipmb** [comment]
I was genuinely curious about this so I took an informal poll on Twitter:

https://twitter.com/lincolnloop/status/570240389958873089
https://twitter.com/lincolnloop/status/570240888120549377

Looks like the majority uses app inside project module, but the jury's out on `setup.py`. In my opinion, it doesn't hurt to have it (people can still install it manually), but without it, the people who want to pip install it can't.

**Comment by gasman** [comment]
Thanks for the explanation and the further research - it's really helpful to know what the current preferred practices are.

We've now had some further discussions at our end about the ideal setup experience for both wagtaildemo and Wagtail in general - particularly around how to avoid having a proliferation of different messages about the best way to install and deploy it. (There doesn't seem to be one single method that's a best fit for everyone - for example, the current dependency on libsass and Pillow as native components means that many devs would prefer to go down the VM route of Vagrant or Docker rather than installing into their local Python environment.)

Our conclusion was that Wagtail itself should aim to remain agnostic about installation tools and project structures, in much the same way that Django's default project template is - and that wagtaildemo should become a demo site hosted by Torchbox for end-users to try out Wagtail, rather than promoting it as something for developers to install to get started. It will still exist as a public Github repo, but more as a reference for how Torchbox does things rather than an endorsement of recommended practices. More generally, we would absolutely encourage Wagtail developers to share their recipes and project templates (as we've done for our currently-preferred Vagrant + Puppet workflow: https://github.com/torchbox/wagtail-cookiecutter).

**Pull request closed without merging**
